version: '3.8'
services:
  frontend:
    build:
      context: .  # Changed from ./test-app to .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network: